### ISSUE TITLE
Compatibility of different KBS/KBC when decrypting/encrypting image

### ISSUE THREAD

**Issue by Xynnn007** [confidential-containers/attestation-agent#113]
#### Background

As stated in [CCv1 security design](https://github.com/confidential-containers/image-rs/blob/main/docs/ccv1_image_security_design.md#image-encryption), there two key fields in the annotation field of an encrypted layer's OCI Discription object in a image manifest:
* `"org.opencontainers.image.enc.pubopts"`: contains public information about the encrypted layer, like `hmac`, `algorithm`
* `"org.opencontainers.image.enc.keys.provider.attestation-agent"`: contains private information about the encrypted layer, like LEK (layer encryption key, the key to encrypt the layer) encryteped by KEK (key encryption key, it is a KBS resource), AEAD's `iv` and `algorithm`

Here, we call the value of `"org.opencontainers.image.enc.keys.provider.attestation-agent"` Annotation Packet.

The annotation entry `"org.opencontainers.image.enc.keys.provider.attestation-agent"` follows [the guide of ocicrypt](https://github.com/opencontainers/image-spec/pull/775/files#diff-ecf63e7090e873922f62c4749c01f63f7eccd42912c1465fbee515cb7c4916c1R423) and the suffix `provider.attestation-agent` is taken by CC community.

![image](https://user-images.githubusercontent.com/22250460/206477857-81d5280b-a07b-4fe6-a15b-a563e9dd9654.png)

However, the layout of Annotation Packet differs from one to one of KBCs in Attestation Agent. For example:
[Offline-Fs-Kbc](https://github.com/confidential-containers/attestation-agent/blob/main/src/kbc_modules/offline_fs_kbc/common.rs#L18) defines
```rust
pub struct AnnotationPacket {
    // Key ID to manage multiple keys
    pub kid: String,
    // Encrypted key to unwrap (base64-encoded)
    pub wrapped_data: String,
    // Initialisation vector (base64-encoded)
    pub iv: String,
    // Wrap type to specify encryption algorithm and mode
    pub wrap_type: String,
}
```

[Eaa-KBC](https://github.com/confidential-containers/attestation-agent/blob/main/src/kbc_modules/eaa_kbc/mod.rs#L26) defines
```rust
struct AnnotationPacket {
    pub kid: String,
    pub wrapped_data: Vec<u8>,
    pub iv: Vec<u8>,
    pub algorithm: String,
    pub key_length: u16,
}
```

[Sample-KBC](https://github.com/confidential-containers/attestation-agent/blob/main/src/kbc_modules/sample_kbc/mod.rs#L23) defines
```rust
pub struct AnnotationPacket {
    // This is an example annotation packet format.
    pub kid: String,
    pub wrapped_data: Vec<u8>,
    pub iv: Vec<u8>,
    pub wrap_type: String,
}
```

> **Warning : The three definitions are different!

This will cause a logic problem that an user can get an encrypted image's manifest and get the annotation entry saying that `provider.attestation-agent`, which means the key provider is attestation-agent, but it does not know the concrete KBC.

This may cause a problem, that I believe most of colleagues who had tried encrypted and decrypted an image using our KBCs have met:
* A image signby KBS `A` cannot be decrypted by KBC `B`.

This will let the users to remember what the exact KBC type to decrypt each image of theirs.
The core reason is that it seems unrational for a `attestation-agent` key provider does not carry enough to indicate the concrete KBC inside a manifest.

#### What we want to improve

We want to make all KBCs in CC's attestation-agent use one format of `AnnotationPacket`.

There are two ways to do this

##### Option 1

![image](https://user-images.githubusercontent.com/22250460/206480699-22ed95d9-6710-41bb-b7b0-b01c50d55383.png)

Let the current Annotation Packet be a wrapper, s.t. the `"org.opencontainers.image.enc.keys.provider.attestation-agent"` value should be defined like
```rust
pub struct AnnotationPacketWrapper {
    // This is an example annotation packet format.
    pub kbc_name: String,
    pub annotation_packet: AnnotationPacket,
}
```

Thus making the kbc type visible to the users.

##### Option 2

![image](https://user-images.githubusercontent.com/22250460/206479593-9a3cdad7-03b2-4c88-9ee9-23468a580311.png)

Let all KBS generated Annotation Packet follow one format.
As we've seen before, what an Annotation Packet contains are:
* data of LEK encrypted by KEK
* id of the KEK to decrypt the LEK
* AEAD algorithm and related params

So, we can define an uniform format of Annotation Packet.
The one of offline-fs-kbc is suggested, s.t.
```rust
pub struct AnnotationPacket {
    // Key ID to manage multiple keys
    pub kid: String,
    // Encrypted key to unwrap (base64-encoded)
    pub wrapped_data: String,
    // Initialisation vector (base64-encoded)
    pub iv: String,
    // Wrap type to specify encryption algorithm and mode
    pub wrap_type: String,
}
```
Because
* The one of Sample-KBC uses `Vec<u8>` for some fields, this will be converted into a long `,`-number-concatenated string. With the layout we suggested, we can use base64 to encode the fields.
* The one of eaa-kbc has an extra `key_length` field, which seems not useful because when a key id
is given, the key is specified.

I **prefer option 2**, for 
* We can reuse those tests of offline-fs-kbc
* When we implement CC-KBC, we can follow this design
* I've checked online-sev-kbc, offline_sev_kbc have same format as offline-fs-kbc, fortunately!

#### Influence

If we use an uniform layout of `AnnotationPacket`, we can actually use `attestation-agent` as the only key provider for all kbcs, which means to handle encrypted images generated from different KBS, and automatically judge which kbc should be used. The concrete KBC type can be decided by `key_id` field due to `KBS_URL` scheme proposed in https://github.com/confidential-containers/documentation/issues/85.

As we may abondon eaa-kbc and sample-kbc when cc-kbc and generic-KBS is prepared, it will not cause much problems for what we do now.

Most importantly, it will influence the behavior of CC-KBC's `KeyProvider` API.

#### What should we do?

* We just need to use uniform `AnnotationPacket` layout for offline-fs-kbc, sample-kbc(can it be abondoned in AA? [already abondoned in image-rs](https://github.com/confidential-containers/image-rs/issues/85)), online-sev-kbc, offline_sev_kbc(I've checked the last two ones have same format as offline-fs-kbc, fortunately!)
* We can leave eaa-kbc not modified for it is used in [kata CI](https://github.com/kata-containers/tests/pull/5234) and [enclave-cc CI](https://github.com/confidential-containers/enclave-cc/issues/13#issuecomment-1333052367). When CC-KBC is prepared, related CIs using CC-KBC and generic-KBS should be added and eaa-kbc can be abondoned then.

**Comment by Xynnn007** [comment]
Hope that the problem I want to state is clear, could you give some comments?
@fitzthum @jialez0

**Comment by fitzthum** [comment]
This is a great proposal. I think we haven't put enough thought into how users will actually build and deploy encrypted container images. It's a big problem if they have to make different images for different KBCs.

I think the second option is ideal. I think the KBC should really be determined by the environment (i.e. the type of enclave determines the KBC) and not by the container image. So KBCs should be as interchangeable as possible. It seems like the best way to do this is to have all the KBCs use the same annotation format.

I don't have a strong preference about which format we use, but the offline-fs-kbc annotation seems fine and is already used in a number of places.

**Comment by stevenhorsman** [comment]
I'm far from an expert on this, but my thoughts are that the KBC used to encrypt an image shouldn't be important for security perspective and having the ability to decrypt the same image with multiple KBC will be very useful in integration tests, but I think is also a better user experience for customers, so option 2 sounds like a winner to me!

**Comment by Xynnn007** [comment]
Now the interface of a KBC defines three functions:
```rust
    fn check(&self) -> Result<KbcCheckInfo>;
    async fn decrypt_payload(&mut self, annotation: &str) -> Result<Vec<u8>>;
    async fn get_resource(&mut self, _description: String) -> Result<Vec<u8>> {
        Err(anyhow!("Get Resource API of this KBC is unimplement!"))
    }
```

The function `decrypt_payload()` is responsible for the following two things:
* Get decryption key using `kid`
* Decrypt `wrapped_data` using the `iv`, `wrap_type` and the key

If we use a same format of `AnnotationPacket`, **I suggest** that change the API of function `decrypt_payload()` from
```
 async fn decrypt_payload(&mut self, annotation: &str) -> Result<Vec<u8>>;
```
to
```
async fn get_key(key_id: &str) -> Result<Zeroizing<Vec<u8>>>;
```

Thus, a KBC can exactly do what we expect it to do -- 
1. Brokering keys (via `get_key`)
2. Brokering confidential resources (via `get_resource`)

If agreed, the decryption related code can be shared by different KBC (like `aes_256_ctr` for `offline-fs-kbs` and `aes-gcm` for `sample-enc`, still, I'll open another pr for document to have a uniform `wrap_type` definition)

**Comment by fitzthum** [comment]
@Xynnn007 

I think this is a great proposal. It doesn't make much sense to have every KBC do the unwrapping separately. I would definitely prefer a more generic `get_key` interface with the unwrapping being standardized.

One thing you might want to add to the road map is updating the sample_keyprovider, which currently has two encryption modules, one for the wrapping used by `eaa_kbc` and one for the wrapping used by `offline_fs_kbc` and `*_sev_kbc`. We should be able to get rid of this modular abstraction.

My two questions are 

1) is a `key_id` going to be enough info to get the correct key from the KBS? We might want this to be extensible so that we can use workload ids or other abstractions to request keys. Is there a good way to support this while still keeping the implementation uniform? 

2) We need to be careful when we make these changes that we update the images that we use for testing. This could break some people's existing images so let's try to document the changes as well as possible and make sure the tests don't break.

**Comment by Xynnn007** [comment]
> I think this is a great proposal. It doesn't make much sense to have every KBC do the unwrapping separately. I would definitely prefer a more generic `get_key` interface with the unwrapping being standardized.

Thanks, definitely agreed. 

> One thing you might want to add to the road map is updating the sample_keyprovider, which currently has two encryption modules, one for the wrapping used by eaa_kbc and one for the wrapping used by offline_fs_kbc and *_sev_kbc. We should be able to get rid of this modular abstraction.

Great, I nearly ignored that. I'll add that. Also, if we agree on a standard process and format for image signing/encryption, the next step I volunteer to edit a simple tool for the whole process of image encryption/signing and register related key on a given KBS.



> 1. is a `key_id` going to be enough info to get the correct key from the KBS? We might want this to be extensible so that we can use workload ids or other abstractions to request keys. Is there a good way to support this while still keeping the implementation uniform?

Nice to answer this question. I'd like to say, yes. This proposal https://github.com/confidential-containers/documentation/issues/85 defines a URL for KBS resources, which helps to locate the key or other kinds of resources straightforwardly. Please feel free to review that proposal and give some suggestions, thanks!



> 2\. We need to be careful when we make these changes that we update the images that we use for testing. This could break some people's existing images so let's try to document the changes as well as possible and make sure the tests don't break.

Up to now, only eaa-kbc uses a different format of `AnnotationPacket`, [sample-kbc has been abandoned in image-rs](https://github.com/confidential-containers/image-rs/issues/85) and is not being used in kata CIs. So the conflict left is only the format of `eaa-kbc` and `*_sev_kbc`.

I'd talked with @arronwy and @hairongchen who are working on kata-cc and enclave-cc CI. Both of the CIs involve eaa-kbc for test now and it seems that eaa-kbc will not be replaced until CC-kbc and cc-kbs are published. I'd suggest that 
* There may be a time until cc-kbc and generic-KBS are ready, we keep on using test images of eaa-kbc or what is used now
* When cc-kbc and generic-KBS are to be published, we can build CIs using the images defined in this proposal and abandon eaa-kbc for some time point (like at the weekly-meeting?)

**Comment by mythi** [comment]
> If we use an uniform layout of `AnnotationPacket`, we can let AA to handle encrypted images which use different key providers, and automatically judge which kbc should be used.

@Xynnn007 if AA is built with multiple KBCs, how to choose which one gets used in option 2? Based on the KBS URL in `key_id` as proposed in https://github.com/confidential-containers/documentation/issues/85?

**Comment by Xynnn007** [comment]
> @Xynnn007 if AA is built with multiple KBCs, how to choose which one gets used in option 2? Based on the KBS URL in `key_id` as proposed in [confidential-containers/documentation#85](https://github.com/confidential-containers/documentation/issues/85)?

Yes, exactly. Could you give some comments about this?

**Comment by mythi** [comment]
> > @Xynnn007 if AA is built with multiple KBCs, how to choose which one gets used in option 2? Based on the KBS URL in `key_id` as proposed in [confidential-containers/documentation#85](https://github.com/confidential-containers/documentation/issues/85)?
> 
> Yes, exactly. Could you give some comments about this?

I did not read it thoroughly yet but perhaps make it more clear in option 2 proposal that it depends on it. Another question I have is related to

> And an image encrypted by key provider module A in CC can be decrypted by key provider B if they have same KEK.

this is misleading because the decryption will always have to go back to the KBS used in encryption if the KBS url is set in `key_id` and because there's always one key provider (`attestation-agent`).



> And an image encrypted by key provider module A in CC can be decrypted by key provider B if they have same KEK.

and 
 adding `<kbc-type>://` to `key_id` during encryption seems to force

**Comment by Xynnn007** [comment]
> I did not read it thoroughly yet but perhaps make it more clear in option 2 proposal that it depends on it. Another question I have is related to

Yes, thanks. I've fixed that.



> this is misleading because the decryption will always have to go back to the KBS used in encryption if the KBS url is set in `key_id` and because there's always one key provider (`attestation-agent`).

Yes. I've fixed it. Before that there is confusion for key provider `attestation-agent` and `kbc`s.
