### ISSUE TITLE
CC-KBC | Provide compilation features for different TEE attesters

### ISSUE THREAD

**Issue by jialez0** [confidential-containers/attestation-agent#140]
Now CC-KBC compiles all the TEE attesters it supports by default, which is redundant. We need to set different features to specify which TEE attester the compiled CC-KBC contains.

cc @fitzthum @Xynnn007

**Comment by Xynnn007** [comment]
Agreed. Now TDX attester needs underlying tdx libs (.so dynamic libs), which seems unuseful for SNP and other platforms. It seems better to only include one attester in one build of cc-kbc. (which implies that different TEE should be provided different guest image)

**Comment by mkulke** [comment]
Does this mean we want to remove the current TEE detection heuristics (`detect_tee_type()`), or would be keep that?

**Comment by Xynnn007** [comment]
> Does this mean we want to remove the current TEE detection heuristics (`detect_tee_type()`), or would be keep that?

Nice catch. I'm in favor of removing that. What's your opinion? @jialez0

**Comment by jialez0** [comment]
> Does this mean we want to remove the current TEE detection heuristics (`detect_tee_type()`), or would be keep that?

@mkulke @Xynnn007 In fact, the feature provided for different `attester` is for the convenience of users who need to use customized guest. For example, some users need the smallest size guest, and some users use the guest version that cannot support the dependency of installing other TEE. In some general production environments, someone still want to use the general version of CC KBC, automatically detect the platform and select attester.

So I think we should at least retain the ability to build universal AA for multiple platforms.
