### ISSUE TITLE
ttrpc | Change path of unix socket

### ISSUE THREAD

**Issue by Xynnn007** [confidential-containers/attestation-agent#147]
It is suggested to change unix socket `unix:///opt/confidential-containers/attestation-agent/getresource.sock` and `"unix:///opt/confidential-containers/attestation-agent/keyprovider.sock"` to `/run/*` as they are temporary data at runtime.

cc @jialez0

**Comment by jialez0** [comment]
@Xynnn007 How about `/run/confidential-containers/attestation-agent/keyprovider.sock` ?

**Comment by Xynnn007** [comment]
@jialez0 it is good to me. also do we need to create the parent directories if not exists in the code?
