### ISSUE TITLE
What is the plan to support SEV/SEV-ES pre-attestation KBC instance?

### ISSUE THREAD

**Issue by haosanzi** [confidential-containers/attestation-agent#16]

**Comment by haosanzi** [comment]
As far as I know, patches in [link](https://github.com/confidential-containers-demo/linux/tree/conf-comp-secret-v3) support to assess secrets from Linux userland. SEV/SEV-ES pre-attestation KBC can use that interface to get the key.

**Comment by jiazhang0** [comment]
> Yeah, we should have support for an offline KBC using pre-attestation and secret injection in the near future. There will need to be some additions to the Kata runtime to drive the setup of the secure channel and injection of the secret. For CCv0 we have a script that the Kata agent can call out to on the host. We also have a sample KBS that knows how to setup this secure channel for SEV(-ES). We're hoping to have an e2e demo of this for November.

Sounds great. We plan to run an e2e demo based on TDX remote attestation with EAA for Nov. Then we will have a full solution to cover two mainstream virtualization based HW-TEEs.
