### ISSUE TITLE
[RFC] Attestation Agent development plan

### ISSUE THREAD

**Issue by jialez0** [confidential-containers/attestation-agent#3]
According to the architecture described in the Attestation Agent Proposal (issue #1):

<img width="735" alt="1" src="https://user-images.githubusercontent.com/35883144/126970725-f66c06ee-2cc8-4067-b2f7-1aacebe131f9.png">

we divide the development work into the following stages:

## Step1: Support the keyprovider call of ocicrypt-rs as a gRPC service

- [ ] Support key provider protocol defined by ocicrypt-rs

- [ ] Run as a long-live gRPC service

## Step2: KBC modularization

- [ ] Define the interaction interface between AA public code and KBC module (as a pub trait)
- [ ] Provide a sample KBC module and a sample KBS (use hard coded key)

- [ ] Improve the sample KBC/KBS using peer-to-peer gRPC service.

Note：Step 1 & 2 are specific to AA archtecture, and step 3 & 4 are specific to AA KBC modularization.

## Step3: Implement E2E attestation demo for kata CC v0 (before Nov. 1)

- [ ] Configurable selection between gRPC and ttrpc.
- [ ] Implement the first group of KBC modules: 

- [ ] SEV(-ES) pre-attestation
- [ ] A KBC module(s) for TDX (ISECL,  EAA or something else?)

- [ ] etc

## Step4: Add more KBC modules

- [ ] ISECL (Intel)
- [ ] GOP (IBM)

- [ ] EAA (Alibaba)
- [ ] UnwrapKey Relaying KBCs

- [ ] Cloud HSMs
- [ ] etc

**Comment by fitzthum** [comment]
On the kata-containers slack @arronwy asked if we should use ttRPC rather than gRPC for ocicrypt-rs and the AA. It looks like we aren't doing that for now, though.

**Comment by hdxia** [comment]
This looks good to me. thanks/Haidong

**Comment by jimcadden** [comment]
This looks good. Thank you, @voidC1326 

Do you know, is someone already working on the `ocicrypt-rs` side of the key provider protocol? 

cc. @arronwy @hdxia

**Comment by hdxia** [comment]
> This looks good. Thank you, @voidC1326
> 
> Do you know, is someone already working on the `ocicrypt-rs` side of the key provider protocol?
> 
> cc. @arronwy @hdxia

@jimcadden, @pravinrajr9 is working on it and will make a pull request in a couple of days.

**Comment by jiazhang0** [comment]
> On the kata-containers slack @arronwy asked if we should use ttRPC rather than gRPC for ocicrypt-rs and the AA. It looks like we aren't doing that for now, though.

There is no objection to take ttrpc as long as AA and ocicrypt-rs can reach an agreement. @arronwy KBS side can continue to use gRPC + ocicrypt's key provider.

**Comment by arronwy** [comment]
> > On the kata-containers slack @arronwy asked if we should use ttRPC rather than gRPC for ocicrypt-rs and the AA. It looks like we aren't doing that for now, though.
> 
> There is no objection to take ttrpc as long as AA and ocicrypt-rs can reach an agreement. @arronwy KBS side can continue to use gRPC + ocicrypt's key provider before ocicrypt also changes to use ttrpc.

The runtime side will use ttrpc first, and Kata agent/ocicrypt-rs/AA will unify with this lightweight solution. BTW golang version ocicrypt also have plan to support ttrpc.

**Comment by voidC1326** [comment]
Thanks for your advice! @fitzthum. After careful discussion within our team, we feel it necessary to implement the interface you mentioned. After improvement, we divide the AA operation process into the following steps:

1. AA starts grpc (ttrpc) service and waits for the request from ocicrypt-rs.
2. When the request arrives, AA parses KBC related parameters to obtain KBC information.
3. According to the information in step 3, AA will query the management list. If there is no corresponding KBC module instance, AA will create the corresponding KBC module instance according to the information obtained in step 3 and call its init interface (if KBC needs to obtain KEK from KBS, it needs to initiate authentication and obtain KEK in the implementation of init interface, And cache KEK in the internal variable of KBC instance); If the corresponding KBC module instance already exists and it has completed initialization, jump to step 5.
4. AA registers the created and initialized KBC module instances in the management list.
5. AA calls the decryption interface of KBC module instance to obtain the returned result, that is, the decrypted optsdata (PLBCO)
6. Receiving the ocicrypt-rs request again, jump to step 2.

**Comment by jiazhang0** [comment]
> > > On the kata-containers slack @arronwy asked if we should use ttRPC rather than gRPC for ocicrypt-rs and the AA. It looks like we aren't doing that for now, though.
> > 
> > 
> > There is no objection to take ttrpc as long as AA and ocicrypt-rs can reach an agreement. @arronwy KBS side can continue to use gRPC + ocicrypt's key provider before ocicrypt also changes to use ttrpc.
> 
> The runtime side will use ttrpc first, and Kata agent/ocicrypt-rs/AA will unify with this lightweight solution. BTW golang version ocicrypt also have plan to support ttrpc.

Sound great. It is necessary to add this configurable selection between gRPC and ttrpc to the task list.

**Comment by sameo** [comment]
>     3. According to the information in step 2, AA will query the management list. If there is no corresponding KBC module instance, AA will create the corresponding KBC module instance according to the information obtained in step 3 and call its init interface (if KBC needs to obtain KEK from KBS, it needs to initiate authentication and obtain KEK in the implementation of init interface, And cache KEK in the internal variable of KBC instance); If the corresponding KBC module instance already exists and it has completed initialization, jump to step 5.
>

Those are implementation details, but I think that the AA should create and instanciate each and every KBC module it supports (The supported list could be an agent build time option). The first init call should be triggered by the first corresponding ocicrypt-rs request AA gets for a given KBC.

 
>     4. AA registers the created and initialized KBC module instances in the management list.
> 
>     5. AA calls the decryption interface of KBC module instance to obtain the returned result, that is, the decrypted optsdata (PLBCO)
> 
>     6. Receiving the ocicrypt-rs request again, jump to step 2.

**Comment by sameo** [comment]
The plan looks pretty good to me. I like the KBC modular approach.

**Comment by fitzthum** [comment]
I wonder if we might want a cleanup interface as well. Some KBCs will connect to stateful KBS/GOP services. We will probably want to cleanup that connection at some point. Might be hard to know when, though.

**Comment by ariel-adam** [comment]
@jialez0 is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?
