### ISSUE TITLE
Image signing verfication & KBS integration Proposal

### ISSUE THREAD

**Issue by liangzhou121** [confidential-containers/attestation-agent#44]
# Overview
According to [CCv1 Image Security Design](https://github.com/confidential-containers/image-rs/blob/main/docs/ccv1_image_security_design.md) design, `image-rs` relies on both `policy.json` and `sigstore` files when it executes container image signature's verification.
- `policy.json`'s [signedBy](https://github.com/containers/image/blob/main/docs/containers-policy.json.5.md#signedby) includes all the public keys that used to verify the image signature.
```JSON
{
    "type":    "signedBy",
    "keyType": "GPGKeys", /* The only currently supported value */
    "keyData": "base64-encoded-keyring-data",
    "signedIdentity": identity_requirement
}
```
- `sigstore` is the configuration file used to obtain the image's signature file.
```
default:
    sigstore: file:///var/lib/containers/sigstore
docker:
    docker.io/my_private_registry:
        sigstore: https://my-sigstore.com/example/sigstore
    registry.access.redhat.com:
        sigstore: https://access.redhat.com/webassets/docker/content/sigstore
```

If the `image-rs` finds that the `policy.json` or `sigstore` files don't exist locally during signature's verification, it will invoke [Attestation-Agent](https://github.com/confidential-containers/image-rs/blob/main/docs/ccv1_image_security_design.md#attestation-agent)'s [Get-Resource service](https://github.com/confidential-containers/image-rs/blob/main/docs/ccv1_image_security_design.md#get-resource-service) interface to fetch them. The format of `getResourceRequest` that AA receives is:
```
message getResourceRequest {
    string KbcName = 1;
    string KbsUri = 2;
    string ResourceDescription = 3;
}
```
The `ResourceDescription` is a JSON used to describe the resource, it's definition as following:
```
{
    "name":"resource_name",
    "optional":{}
}
```
The `ResourceDescription.name` specifies the resource name to fetch (`policy.json` or `sigstore`).

# Prerequisite
- The KBS must be a trusted service that has been verified by AA.

# Proposal
It mainly discusses how to define the resource group's identity in `ResourceDescription.optional` and how to pass it to Sandbox.

## Option 1
One KBS only supports one set of `policy.json` and `sigstore` files, that is, when KBS receives a `getResourceRequest` request, it will always returns the same `policy.json` or `sigstore` file. The `getResourceRequest.ResourceDescription` definition will be:
- Fetch `policy.json` file:
```JSON
{
    "name":"image_signing_verfication_policy",
    "optional":{}
}
```
- Fetch `sigstore` file:
```JSON
{
    "name":"image_signing_verfication_sigstore",
    "optional":{}
}
```

### Advantage
Easy to deploy:
- AA side: As long as AA send a unified `getResourceRequest` request to KBS, it can get the required file.
- KBS side: Just add a single set of `policy.json` and `sigstore` files to the KBS

### Weakness
Different sandboxes will use the same set of `policy.json` and `sigstore` files for signature verification, so it cannot implement differentiated deployment of policies between different sandboxes.

## Option 2
One KBS supports multiple sets of `policy.json` and `sigstore` files. The `resource_id` needs to be specified in `ResourceDescription.optional` when AA sends `getResourceRequest` request to KBS. 
The `ResourceDescription.optional` definition will be:
```JSON
{
    "name":"resource_name",
    "optional":
    {
        "resource_id" : "xxxxxxxx"
    }
}
```
- resource_id: defined by ResourceId(defined in ResourceId section)

### Advantage
Differentiated deployment strategies can be implemented for different Sandboxes.

### Weakness
The ResourceId(defined in ResourceId section) needs to be passed into sandbox during it's deployment. It will add deployment complexity for Sandbox.

# ResourceId
The `resourceId` is a set of `policy.json` and `sigstore` files identity inside KBS. It's generated by KBS and should be passed to Kata sandbox during deployment.

## Generation
KBS will return a `uuid` when a set of `policy.json` and `sigstore` files is added into KBS. The `uuid` equals to `resourceId`.

## Delivery
The `resourceId` can be passed to the Kata Sandbox via the agent config file (`agent-config.toml`). So the new `image_signing_verfication_resource_id` needs to be added:
```
aa_kbc_params = "eaa_kbc::123.56.152.133:30000"
image_signing_verfication_resource_id = "xxxxxxxx"
debug_console = true
dev_mode = false
log_level = "debug"
#hotplug_timeout = 3
debug_console_vport = 1026
log_vport = 0
container_pipe_size = 0
server_addr = "vsock://-1:1024"
unified_cgroup_hierarchy = false
tracing = false

[endpoints]
allowed = [
        "AddARPNeighborsRequest",
        "AddSwapRequest",
        "CloseStdinRequest",
        "CopyFileRequest",
        "CreateContainerRequest",
        "CreateSandboxRequest",
        "DestroySandboxRequest",
        # "ExecProcessRequest",
        "GetMetricsRequest",
        "GetOOMEventRequest",
        "GuestDetailsRequest",
        "ListInterfacesRequest",
        "ListRoutesRequest",
        "MemHotplugByProbeRequest",
        "OnlineCPUMemRequest",
        "PauseContainerRequest",
        "PullImageRequest",
        "ReadStreamRequest",
        "RemoveContainerRequest",
        # "ReseedRandomDevRequest",
        "ResumeContainerRequest",
        "SetGuestDateTimeRequest",
        "SignalProcessRequest",
        "StartContainerRequest",
        "StartTracingRequest",
        "StatsContainerRequest",
        "StopTracingRequest",
        "TtyWinResizeRequest",
        "UpdateContainerRequest",
        "UpdateInterfaceRequest",
        "UpdateRoutesRequest",
        "WaitProcessRequest",
        "WriteStreamRequest"
        ]
```

**Question**: How to pass the parameter dynamically in a more flexible way than through agent config?

**Comment by liangzhou121** [comment]
>as an advantage for option 2. I can see how that's a use case; however, I don't see a need for the sandbox to "know" which sigstore it should get before attestation. If the guest owner only wanted to provide certain sigstores depending on some feature a sandbox has, it should provide them through the KBS depending on successful attestation of that feature or property, no? Therefore, I don't see the point in setting a static resource ID.

Yes, it's better to implement the negotation process automatically. But currently we have no idea about what sandbox's feature or property that can be sent to KBS to fetch the correct `sigstore` file.  Do you have any suggestion about this?

>Are you suggesting the guest also runs some e.g. cryptographic check towards the KBS? With the guest owner's successful attestation of the guest, and the establishment of a secure channel that comes with it, I don't really see what attack vector this would be mitigating

I remember that we have already reached aggrement that AA should also need to check KBS idenetity.  @jiazhang0 can you help to add some comments about this question?

**Comment by jiazhang0** [comment]
> Are you suggesting the guest also runs some e.g. cryptographic check towards the KBS? With the guest owner's successful attestation of the guest, and the establishment of a secure channel that comes with it, I don't really see what attack vector this would be mitigating.

The so-called "The KBS must be a trusted service that has been verified by AA." just means the KBS has been authenticated by AA when initializing the attestation, e.g, through regular HTTPS protocol. The initial discussion about KBS authentication was discussed in https://github.com/confidential-containers/image-rs/issues/2#issuecomment-988787074.

**Comment by fitzthum** [comment]
I think this is a reasonable proposal. I'm not sure how necessary the second option is, but I guess it's optional so we might as well let people use it if they want to.

The content of a pod is dynamic. A guest owner may have some set of signed containers but they might deploy pods with various combinations of these containers. The guest owner needs to make sure that whatever pod is deployed, the correct information makes it into the enclave to verify the containers in the pod. The dynamic nature of the pod might make it seem like we need a way to select different policy files, but do we really? 

The policy and sigstore files allow the guest owner to specify multiple registries. In most cases it seems likely that a guest owner would simply use one policy file that contains information about all of the registries they use. They can supply this to whatever pod they need to (assuming that the launch measurement checks out) and it will cover all of the containers that they trust. As the proposal points out, the guest owner would be using the same deployment policy for every pod regardless of environment.

So the question is really whether there are use-cases where the guest owner might want to have different policies. When it comes to provisioning secrets, I think it's reasonable for a guest owner to conditionally provide secrets based on a launch measurement. They might want to allow certain encrypted containers to run only on the newest firmware version or inside of an enclave with particular features. If we want something similar with signatures, the KBC will need to request an appropriate policy by id. Then the KBS can validate the measurement against the requirements for the requested policy and provide the policy if valid. Is this level of scrutiny really necessary for signatures, though? If there is a container that the guest owner only wants to run in a particular environment, that container should probably be encrypted, right? What threats come from providing the public key of a registry to a pod running in an enclave with older firmware?


One thing that this discussion has brought up is that we don't really have any way of identifying a pod to the KBS. With an online KBS, the KBS sees one layer decryption key request at a time and releases that based on a launch measurement. The KBS doesn't really know what the pod looks like (although it would know that certain requests come from the same connection). Maybe this is something to consider as we think about broader Kubernetes integration. Would it help us if the KBS new more about the orchestration? 


Finally, we should make sure that the resource format is extensible to other types of resources that we might want in the future. So far it looks alright. I notice that the protocol returns one field of bytes. Is there any chance that we might want an additional information field that could be populated alongside the resource? Also, do we have a plan for passing two resources `policy` + `sigstore` in one field of bytes?


Finally (again), I haven't gotten around to moving the `aa_kbc_params` field to the pod annotation where I think it belongs. Hopefully that can happen as part of CCv1. I think it will require a little bit of messing around.

**Comment by liangzhou121** [comment]
>Is it really the sandbox self-reporting its features to the KBS? Let me try an example and you can tell me whether that's the use case you were thinking of. To avoid any confusion with real-world technologies, let's say there are versions 50 and 51 of a runtime-attestation-based TEE called CoolTEE; and there is some minor flaw in version 50 such that the workload owner wouldn't want to run workload A on it, but workload B is okay. Then, I would assume the KBS would be able to attest it is talking to a CoolTEE v51, and only give the workload A sigstore to that TEE. Conversely, I would not see why one would want to specify a resource ID in the image. (Also, such a distinction should most especially cover decryption keys -- verification signatures would be secondary.)

Yes, the KBS attestation can ensure the CoolTEE is trustworthy, and KBS can send (`policy.json` + `sigstore`) files to it directly. And I think you point that "verification signatures would be secondary" is reasonable. It should safe to send a global `policy.json` which maybe includes multiple public keys and other info to CoolTEE. So the **Option 1** should be better in this situation.

**Comment by liangzhou121** [comment]
>Finally, we should make sure that the resource format is extensible to other types of resources that we might want in the future. So far it looks alright. I notice that the protocol returns one field of bytes. Is there any chance that we might want an additional information field that could be populated alongside the resource? Also, do we have a plan for passing two resources policy + sigstore in one field of bytes?

We think the current `getResourceRequest` request is extensible because it includes `ResourceDescription.name`. So this request can specify the exact resource it want to fetch. 
As example: `image-rs` will fetch needed resource as demand.
- It will send following `getResourceRequest.ResourceDescription` to fetch `policy.json` if it finds the file isn't exist locally.
```
{
    "name":"image_signing_verfication_policy",
    "optional":{}
}
```
- It will send following `getResourceRequest.ResourceDescription` to fetch `sigstore` if it finds the file isn't exist locally.
```
{
    "name":"image_signing_verfication_sigstore",
    "optional":{}
}
```

**Comment by liangzhou121** [comment]
@fitzthum Thank you for your comprehensive explainations. We also reached agreement internally that the **Option 1** should be better base on the explainations. Following are the updated Option 1:
# Option 1
One KBS only supports one set of `policy.json` and `sigstore` files, that is, when KBS receives a `getResourceRequest` request, it will always returns the same `policy.json` or `sigstore` file. 
The `ResourceDescription.optional` definition will be:
- Fetch `policy.json` file:
```
{
    "name":"image_signing_verfication_policy",
    "optional":{}
}
```
- Fetch `sigstore` file:
```
{
    "name":"image_signing_verfication_sigstore",
    "optional":{}
}
```
Do you think this description is appropriately?

**Comment by fitzthum** [comment]
LGTM. If some people want to have more flexible policy/sigstore deployment they can implement a KBS/KBC that uses the optional field

**Comment by liangzhou121** [comment]
**Conclusion**:
Option 1 will be selected as default solution.
If some people want to have more flexible policy/sigstore deployment, the `getResourceRequest.ResourceDescription.optional` field can be used by KBS/KBC to reach this.

**Comment by ariel-adam** [comment]
@liangzhou121 is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by liangzhou121** [comment]
> @liangzhou121 is this issue still relevant or can be closed? If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

Yes, this functionality has already been implemented inside AA and it can be closed now.

**Comment by ariel-adam** [comment]
Cool, closing the issue
