### ISSUE TITLE
Extract AA core functions as a rust library to support enclave-cc

### ISSUE THREAD

**Issue by jialez0** [confidential-containers/attestation-agent#53]
In the architecture of enclave-CC, sometimes only one process can run in enclave (such as Gramine), so the core function of AA needs to be integrated into the agent program as a rust library crate. But the current implementation of AA is a grpc service application. Therefore, if AA want to support enclave-CC, we need to transform the current AA architecture and separate the core function (including KBCs) and the part of grpc service into two rust crates, the former as library crate and the latter as application crate.

I'm not sure about the description of this work in the current development plan of enclave-CC. It may take some time and some tests to complete this work, but it may be a necessary work for AA to support enclave CC.

FYI @sameo @fitzthum  @jodh-intel @jiazhang0

**Comment by jiazhang0** [comment]
@YangLiang3 @hdxia @bigdata-memory @ying2liu This requirement comes from the second milestone of enclave-cc: `enclave-agent as a single process needs to integrate attestation-agent as internal module/service. `

And the further discussion occurs here: https://github.com/confidential-containers/enclave-cc/issues/7

**Comment by YangLiang3** [comment]
> @YangLiang3 @hdxia @bigdata-memory @ying2liu This requirement comes from the second milestone of enclave-cc: `enclave-agent as a single process needs to integrate attestation-agent as internal module/service. `
> 
> And the further discussion occurs here: [confidential-containers/enclave-cc#7](https://github.com/confidential-containers/enclave-cc/issues/7)

sure, I think this situation is like "inclavared" we met before.

**Comment by jialez0** [comment]
If we want to support encrypt CC, `ocicrypt-rs` and the signature verification modules of `image-rs` may also need to do some adaptation. At present, the way that `ocicrypt-rs` and `image-rs` signature verification modules call AA's API is gRPC, but as mentioned above, AA will become a trust library crate in enclave-cc, so the caller of AA also needs to do some adaptation. @arronwy @YangLiang3 @jiazhang0
