### ISSUE TITLE
SEV-SNP Support in CC-KBC

### ISSUE THREAD

**Issue by fitzthum** [confidential-containers/attestation-agent#59]
This is an extension of #58 

The generic KBC will need to support SEV-SNP meaning that it will need to get the attestation report from the PSP and format the evidence. The evidence will include the attestation report. If we use measured direct boot, the evidence should also include the hash of the kernel, initrd, and kernel cmdline.

**Comment by ariel-adam** [comment]
@fitzthum is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by fitzthum** [comment]
Still relevant. See the SEV-SNP enablement board for all the SNP-related issues.

**Comment by ariel-adam** [comment]
Ack, we need to decide if we want a single board to track the work for different releases or multiple boards 
if it's multiple boards we will need to review multiple boards on project meetings to provide visibility to our progress 
We could simply add another customized fields for SEV-SNMP related issues in the CoCo release board so we could the issues both on the V0.2.0 tab and on a new tab we'd created for you called SEV-SNMP support

Would that work?

**Comment by fitzthum** [comment]
See https://github.com/confidential-containers/attestation-agent/pull/105
