### ISSUE TITLE
KBS Url and KBC name mapping's configuration

### ISSUE THREAD

**Issue by liangzhou121** [confidential-containers/attestation-agent#6]
Previously we have discussed and reached agreement that Attestation Agent used KBS Url and KBC name mapping should be passed via key provider protocol. So this issue is targeted to discuss how to configure and store this mapping configuration.

According to @sameo suggestions, we have following 3 options:
- Pass the selected KBC as a pod annotation. The kata-agent would get that information and then pass it down to the AA.
- Use a guest owner defined and measured mapping between platforms (TDX, SEV, etc) and KBC. This could be part of the kata-agent configuration file and would leave it to the kata-agent to detect the hardware platform and then select a KBC.
- Use a guest owner defined and measured mapping between KBS hosts and KBC. This is fairly similar to the previous option, in the sense that the kata-agent would parse that information and select a KBC to be passed down to the AA.

And according to @fitzthum , the option 1 is simple and should be better to start from.

But we still encounter following questions:
- What's these configuration's detail format? Like:
    - kbc_name: iscel & kbs_url: https://my-cloud.com/tenant-foo/kbs ?
- Who will parse this mapping configuration and pass to AA via key provider protocol ?
- How to embed kbc_name and kbs_url parameters into current key provider protocol ?

**Comment by liangzhou121** [comment]
Proposal:
we propose to add following new filelds into kata agent configuration file.
```
# Pass the parameters that used by attestation agent't common framewrok
[attestation agent]
kbc_name = isecl                 # isecl, eaa or gop ...
kbs_url = https://my-cloud.com/tenant-foo/kbs 

# Pass the parameters that used by specific KBC module. This field should be empty by default.
[kbc private]
$(KEY1) = $(VALUE1)
$(KEY2) = $(VALUE2)
...
```

As AA will always receive these prarameters from key provider protocol. So these new fields also need to be added into protocol.
```
{
     "op":"keyunwrap",
     "keyunwrapparams":{
         "dc":{
             "Parameters":{
                 "attestation_agent":[
                      “kbc_name : xxxxx",
                      "kbs_uri : xxxxx",
                      "$(KEY1) : $(VALUE1)",
                      "$(KEY2) : $(VALUE2)",
                      ...
                  ],
                 "DecryptConfig":{
                     "Parameters":{}
                 }
             }
         }
    }
    “annotation": #kbs-protocol-specific 
}
```

About who will parse the kata config file to get these new added fields, we think both kata agent and ocicrypt-rs should be OK.

Hi @sameo @fitzthum @arronwy, Do you have any comments and suggestations about this?

**Comment by arronwy** [comment]
Just synced with @liangzhou121 , we have three types of data required by attestation agent, one is "keyid" which is container layer specific info will store in container image content descriptor annotations, “KBS URL” and “KBC name” which are tenant specific info, to avoid duplicate, we may store them at container image manifest annotations. If we want more secure way to store them, put them in pod annotation is also a good option.  BTW when we need run multiple encrypted containers from different verndor in one pod, we still need associate these info at container level. Any suggestions? @hdxia  @jiangliu
