### ISSUE TITLE
offline_fs_kbc: Add support for get_resource API to enable signature verification with local attestation

### ISSUE THREAD

**Issue by stevenhorsman** [confidential-containers/attestation-agent#63]
**As a** user of the attestation-agent with the offline_fs_kbc module
**I want to** be able to get the policy, sigstore config and public GPG details
**so that** I can use them for signature verification

### Description

In order to remove the dependency on Confidential containers `skopeo` for our [local/offline attestation scenario](https://docs.google.com/presentation/d/1vVN97q3bosJbjyco4dd_25PfnIYNaK3Kg_wCAmvmS4c/edit#slide=id.g132c3a0b3c7_0_10), one of the things we want, is for the `offline_fs_kbc` KBC to support signature verification through `image-rs` (see [#kata-containers/kata-containers4581](https://github.com/kata-containers/kata-containers/issues/4581) for more information).

To do this I believe the Offline filesystem KBC needs to handle the `Policy`, `Sigstore Config` and `GPG keyring` getResource requests. At the moment it only seems to support the [`decrypt_payload`](https://github.com/confidential-containers/attestation-agent/blob/main/src/kbc_modules/offline_fs_kbc/mod.rs#L33) API, so we want to extend it to support the [`get_resource` interface](https://github.com/confidential-containers/attestation-agent/blob/dfb0f1e85c5f498f11b28c71394d68eec8f013a6/src/kbc_modules/mod.rs#L26) as well, like the `eaa_kbc` does. I'm guessing that this requirement is also applicable to the `offline_sev_kbc` as well, so that might need an equivalent issue.

In absence of a better design (which might exist and I just can't find), we could add a new file, called something like `aa-offline_fs_kbc-resources.json` (as a companion to [`aa-offline_fs_kbc-keys.json`](https://github.com/confidential-containers/attestation-agent/blob/main/sample_keyprovider/src/enc_mods/offline_fs_kbs/README.md#usage)) and read the requirement fields from there based on their field names.
We might want to consider if a single json file should support multiple public gpg keys, but I'm not sure if the `image-rs` code base that we want to integrate with handles these. I'd be interested to know how EAA/verdictd are configured and if there is anything we could learn from them.

### Update

Since I originally wrote this issue, similar function has been written for the sample_kbc, so using #69 as a base is probably a good way to start and the code not too different to what I'd expect we need.

**Comment by fitzthum** [comment]
I thought that `image-rs` tries to read the policy from the filesystem before using the `get_resource` endpoint (is this correct @arronwy ?). If we are using the `offline_fs_kbc` we might as well just put the policy in the filesystem and have `image-rs` read it directly, although I guess it might be a slightly more thorough test to have use `get_resource`." 

I am going to be adding `get_resource` support to `offline_sev_kbc` (soon to be `online_sev_kbc`), so you may be able to steal some of that code if nobody else gets around to doing it.

**Comment by stevenhorsman** [comment]
@fitzthum - thanks for the response Tobin! Arron and I did chat about this a bit in the past and whether the `get_resource` approach, or just laying files in the right place in the rootfs was the way to go. I think my opinion is that them all being in a single place (the offline_fs json file) would be an easier user experience and I didn't know if we wanted to document the hard-coded file locations (which I think are for testing at the moment).
I'm far from an expert though, so very happy to hear opinions and if we can copy the `offline_sev_kbc` implementation that sounds like it might be a good plan :)

**Comment by arronwy** [comment]
> I thought that `image-rs` tries to read the policy from the filesystem before using the `get_resource` endpoint (is this correct @arronwy ?). If we are using the `offline_fs_kbc` we might as well just put the policy in the filesystem and have `image-rs` read it directly, although I guess it might be a slightly more thorough test to have use `get_resource`."

Hi @fitzthum , current  `image-rs` will check whether pubkey/policy file is saved in the directory in trusted memory,if not it will try to get from attestation-agent `get_resource` API, after the rootfs is integrity protected by some mechanism like dm-verify, we may can also use the file in the rootfs. @jialez0 may give more comments here.

**Comment by stevenhorsman** [comment]
Note: This comment might be useful: https://github.com/confidential-containers/attestation-agent/pull/69#pullrequestreview-1057434357 :)

**Comment by liudalibj** [comment]
@stevenhorsman From the [sample policy.json](https://github.com/containers/image/blob/main/docs/containers-policy.json.5.md#a-reasonably-locked-down-system) it seems that we do not need multiple policy files, we can define multiple repos in one single policy file. But we need support to get public gpg keys for different repo from AA side.

**Comment by stevenhorsman** [comment]
> @stevenhorsman From the [sample policy.json](https://github.com/containers/image/blob/main/docs/containers-policy.json.5.md#a-reasonably-locked-down-system) it seems that we do not need multiple policy files, we can define multiple repos in one single policy file. But we need support get public gpg keys for different repo from AA side.

Yes, I agree - only a single policy is required - sorry for the confusion caused in my description and whilst sometimes having multiple `registries.d`/sigstore config files can be helpful for separation, I think it's possible to do everything in a single one, so that's probably fine as well.

If you can talk to the rest of the attestation-agent/image-rs team about support for multiple public gpg keys (just making the json file field take an array for us could work, but we'd need to ensure that the resourceDescription was aligned) that would be great, but also I think it might be best to create a separate issue for supporting multiple public GPG keys and just focus on a single one at this point?

**Comment by liudalibj** [comment]
> If you can talk to the rest of the attestation-agent/image-rs team about support for multiple public gpg keys (just making the json file field take an array for us could work, but we'd need to ensure that the resourceDescription was aligned) that would be great, but also I think it might be best to create a separate issue for supporting multiple public GPG keys and just focus on a single one at this point?

@stevenhorsman yeah, I will focus on a single one in this issue, and create a new issue to support multiple public GPG keys for offline_fs_kbc.
 
I talked the multiple public GPG keys issue with @arronwy @jialez0 and @Xynnn007, currently the `get_resource` API `ResourceDescription` support the caller add a `optional` json map, the caller can use something like `"optional": {"repo":"docker:hostname:5000/myns/sigstore-signed-with-full-references"}` to get public keys for `hostname:5000/myns/sigstore-signed-with-full-references` transport in the [sample policy.json](https://github.com/containers/image/blob/main/docs/containers-policy.json.5.md#a-reasonably-locked-down-system), if there are multiple public GPG keys be used for one transport, maybe just return the keys in a json array with correct order.

Maybe some new issue need be created in `image-rs` repo to support  multiple public GPG keys  @Xynnn007 would you like help to create it?

**Comment by liudalibj** [comment]
@stevenhorsman I would like the` aa-offline_fs_kbc-resources.json` file follow this template
```json
{
  "policy.json": "json string of policy.json",
  "sigstore_config.yaml": "<BASE64-ENCODED-DATA of sigstore_config.yaml>",
  "pubkey.gpg": "<BASE64-ENCODED-DATA of pubkey.gpg>"
}
```

The base64 encode string can be created by end user by
```
cat <path-to-file> | bas64
```


An example file looks like:
```
{
  "policy.json": {
    "default": [
      {
        "type": "insecureAcceptAnything"
      }
    ],
    "transports": {
      "docker": {
        "quay.io/kata-containers": [
          {
            "type": "signedBy",
            "scheme": "simple",
            "keyType": "GPGKeys",
            "keyPath": "/run/image-security/simple_signing/pubkey.gpg"
          }
        ]
      }
    }
  },
  "sigstore_config.yaml": "ZG9ja2VyOgogICAgcXVheS5pby9rYXRhLWNvbnRhaW5lcnMvY29uZmlkZW50aWFsLWNvbnRhaW5lcnM6CiAgICAgICAgc2lnc3RvcmU6IGZpbGU6Ly8vZXRjL2NvbnRhaW5lcnMvcXVheV92ZXJpZmljYXRpb24vc2lnbmF0dXJlcwogICAgICAgIHNpZ3N0b3JlLXN0YWdpbmc6IGZpbGU6Ly8vZXRjL2NvbnRhaW5lcnMvcXVheV92ZXJpZmljYXRpb24vc2lnbmF0dXJlcw==",
  "pubkey.gpg": "LS0tLS1CRUdJTiBQR1AgUFVCTElDIEtFWSBCTE9DSy0tLS0tCgptUUlOQkdGTVZFZ0JFQUN6ZC9ISno2bnE4R0FqRm9XdDIwUGhBeTRScDhxNHFlRkUzSkorbHdoUHprSmRiTDNaClFKMzFURUNyYktVeW8zTElRMzFCNzVBWXczdm5FSVVPY3V0U0UxaThvNTU3SW94eGxHNFN3dGtSVmRVUGVFN2UKdElOMm1aKzJHd25nQW1KRUgxNWtNQUZzVVFhNG4rWE9WUU9aSTNRWWVsWWpMd0thbXFBa3dFdjAzSmpHaTIrbQo0a0ZITzBmMy9lc0pmZXhVd3hLMHdQazJ4emlvZ2FpTzN6NDViTkoxMDZwSC95NGhRMHBWbWZJSHpPVjZwRHN2ClVHcTFxdnZlL2dDRXFZZWYvcUgyNzJoRkdNTE1qRy8yOStwVmZ1bEJ2YnpiUUhNUHlIaTFBdTVwemJWVUhxOUEKOURoWXhmWllpN2MreXU5Y1h0cngzQmlXSG52NzlBRUtWZDhCdkVucE02dGNIOWMvVFJlakd6VjF0cThva05wMwpXaXp6T0ZzVXBpaXVYVVo5ZlVlQ0s5YnVEaXdsdDF2ZGQ2OG5RZ3o2YkdIOEZqbVd2UXU4eTNVZEZRSTUwQkNVCmVEeFZEcHIzRXhjNER6MWxnU0pNV0wya2NJRy8wVllGU2hkRXUxL2lnNmdLUlpGcm1XN2hnSU51V1ZwWUNoZGkKK0I3Rkg1UDhGUlBiN0YrZFdyY0o3M3A1WXJLMzhHbnpadTNtdmZSUnk5Q0FpU1NFNFpEd0JuMjMzSCtlMFFzWAptT2lIcW1LSVZTbnhVa1hoTktXWm9LUDVQRlBHWE9YSEFNaWRnWC8wT0UxOEc2WmREMEYvRVNuYVdUL2lwNzNNCk1EYU5tVENlL2JZdW9TZy9oVUdCMEtENUx2aFZaT01haTh1MkYwQnJFYWdPRnQ3SkZjbUVwd2pXWndBUkFRQUIKdEVsVGRHVjJaVzRnU0c5eWMyMWhiaUFvUjFCSElHdGxlU0JtYjNJZ2MybG5ibWx1WnlCcllYUmhJSFJsYzNRZwphVzFoWjJWektTQThjM1JsZG1WdVFIVnJMbWxpYlM1amIyMCtpUUpZQkJNQkNBQkNGaUVFWjdKS3JNUlpaNTRDCmc5ZnVXUGJ0Qis2bXRDa0ZBbUZNVkVnQ0d3TUZDUUhoTTRBRkN3a0lCd0lESWdJQkJoVUtDUWdMQWdRV0FnTUIKQWg0SEFoZUFBQW9KRUZqMjdRZnVwclFwc3ZBUC8zTit5RGRlRkRMaVdSS21YbEhzbWRuT3dlYVdxQjdzUWJ0SQpJTFh6RVFCY1pIWjFRNUxna0o2bzlHUlJlK0pPVmFsQUQ5QXdPQjg4Z0hNVVptR2hmQU05dnY3R3RWWGdpQkNmCi9mNDE0TTFueS9xMUgwZG1wRnF4b3FaYzlXNlhaU1pFVC8yNVFPUlMzYkxIK0dFdnQ4enZaUkFLVU9WRUhPZTQKbHRocmNuY21uaFd4ZWc0ZFJGWEZRczJZSW41VzZiOTd4SzN4emF0bDlyTVgwd2s4L2xweDlHQ0tLalZ3OVpQcwpUZ25kcmlMTnUzaGJOeWFXaEhlTHFUT1hEOUU0WUNjM3FMc0MvZW5Hclh6Si91bWdpaHUvRy9iNWFsZWZ6U09xCnh0MHI2ejdSbk85OXJVdEtDYW0rNUVEa0t6VXZoamdSM2oyTGtHWkMxZnFBTnQ2TEtPK0MwT3FtMEpUMm1UZGEKdGEveDdCdGozNktJYjN1TlNSdDJiRHJGWXhPajZzRnlQVlRVbHpOZ2l0bkszVHFJeG5teWlHZGhPVUcyc1p5OAowSTFaNHZaT0JGdzIzWE9qYzRUVGRWU29BbUxSZkhOeWZtYXlHbS9ja2xlTjV2T2xiVzlPOXREa0M0alo2WkZNCjFxZzEyUkxvS1dxRXRodmlzOVhzV0xieEFBaG0xbkZKV0VpTlhzdW1NUDc0U1cwLy9qYmRFT0xObzBXRG5TTmIKZ3U2a2hVYXJIR0dpUEJzeFc4cURGdXNIWFplMEpDSVFRUTBDZVh3T1owaXFINC9tQ0lKQnlId2dEdExnbnNUTQo2a2hnU2VhMXk1a3RRQnZSdU1QODg5ZWJQSEoyNjFqeUl5OXV5K25oaUt5cG9PK3lqMWYvUm5qNWtLS3Y3Mm5LCjV1RVNwSkJUCj1CN3ZRCi0tLS0tRU5EIFBHUCBQVUJMSUMgS0VZIEJMT0NLLS0tLS0K"
}
```
The sample encode string is base on [pubkey.gpg](https://github.com/confidential-containers/attestation-agent/blob/main/src/kbc_modules/sample_kbc/pubkey.gpg) and [sigstore_config.yaml](https://github.com/confidential-containers/attestation-agent/blob/main/src/kbc_modules/sample_kbc/sigstore_config.yaml) under `sample_kbc` folder.

What's your comment about this?

**Comment by stevenhorsman** [comment]
That looks like a good initial solution and as I mentioned to you earlier I think we are at the stage to get something out there that works and is decent and then we can work on finessing the technical solution/user experience later.

**Comment by liudalibj** [comment]
The https://github.com/confidential-containers/attestation-agent/pull/78 is created please help to review and comments @stevenhorsman @fitzthum @jialez0 @Xynnn007
Only support one key in this initial pr, will handle the multiple public GPG keys in a new issue.
