### ISSUE TITLE
Async KBC trait?

### ISSUE THREAD

**Issue by fitzthum** [confidential-containers/attestation-agent#65]
I've been working on an `online_sev_kbc` and I'm realizing that it is quite a pain to make async gRPC requests from the KBC module because the KBC trait methods are not async. It seems like this might be a problem for the `CC-KBC` as well. Do you have any plan for this? @jialez0

**Comment by jialez0** [comment]
Thanks for reminding, this is indeed an important problem we face. Maybe we can modify KBC trait in a new PR to make it asynchronous, and modify all KBCs, which should be necessary. But I'm not sure if this will cause problems for some KBCs at present.

**Comment by fitzthum** [comment]
I think the `offline_fs_kbc` and `offline_sev_kbc` should be fine.

Currently there is a mutex in the gRPC functions. We use the mutex to lock the AA object before calling `decrypt_image_layer_annotation` and `download_confidential_resource`. We need to do this because both of these functions could instantiate new KBCs and thus change the internal state of the AA object. If we make `decrypt_image_layer_annotation` and `download_confidential_resource` into async functions, we will probably need to use `tokio::sync::Mutex` rather than the standard one. The standard mutex can't be held across an await.

That said, I'm not sure that it's a good idea to hold any mutex while awaiting. We don't want to lock a mutex and then immediately deschedule the thread by awaiting. Instead I think we might want to refactor the AA trait a little bit. We should think about adding a new method that takes a KBC name and then updates the internal state of the KBC if necessary. This function would be `sync`. Then we can remove that functionality from`download_confidential_resource` and `decrypt_image_layer_annotation`. This way we would only need to hold the mutex while we call the first `sync` function. Does that make sense?

I am also a bit worried that the AA struct is not `Send`-able. I've done a bit of testing and run into some problems with it.

**Comment by jialez0** [comment]
> That said, I'm not sure that it's a good idea to hold any mutex while awaiting. We don't want to lock a mutex and then immediately deschedule the thread by awaiting. Instead I think we might want to refactor the AA trait a little bit. We should think about adding a new method that takes a KBC name and then updates the internal state of the AA if necessary. This function would be `sync`. Then we can remove that functionality from`download_confidential_resource` and `decrypt_image_layer_annotation`. This way we would only need to hold the mutex while we call the first `sync` function. Does that make sense? We might still have problems with the state of the KBCs themselves. Are we going to need a mutex to protect that?
This may indeed improve the efficiency of AA in processing requests, but it will prevent us from caching the key obtained from KBS in the KBC structure when decrypting layer annotation, but maybe we can cache the key in another way (such as writing to a file).

> I am also a bit worried that the AA struct is not Send-able. I've done a bit of testing and run into some problems with it.
What is the specific problem?

**Comment by fitzthum** [comment]
Ok I sorted out the issue with the AA struct. There is now PR https://github.com/confidential-containers/attestation-agent/pull/66. This doesn't change the usage of the mutex that I was complaining about above. For now I think it's more important to continue working on the new KBCs. We should come back to the mutex later.

**Comment by jialez0** [comment]
Solved by #66
