### ISSUE TITLE
Add optional registry credential information to the get_resource

### ISSUE THREAD

**Issue by stevenhorsman** [confidential-containers/attestation-agent#92]
### Description

In order to support the ability to pull image from authenticated registries we want to add support for image-rs to get credentials from the attestation-agent (via the KBC) in a similar way to how we flow the sigstore/policy/public GPG keys for signature verification.

From previous discussions in https://github.com/kata-containers/kata-containers/issues/4888#issuecomment-1263344248 @Xynnn007 suggested:

> For the problem you've mentioned here, I think we can create new `ResourceDescription` request message like
> ```json
> {
>     "name": "credential",
>     "optional": {
>         "registry": "...",
>     },
> }
> ```
> 
> following the definition of `ResourceDescription` in AA https://github.com/confidential-containers/attestation-agent/blob/79592180736a6009086040b63b5424e86e330e83/src/kbc_modules/mod.rs#L133
> 
> And then as you said, the credential will be sent from KBS in base64 encoded.

Which I think it a good starting point.

I think in the short term (like with signature verification) we should just focus on credentials for a single container registry/repository to start with and worry about multi registry support later.

**Comment by liudalibj** [comment]
@stevenhorsman @Xynnn007 @jialez0 I create [a pr](https://github.com/confidential-containers/attestation-agent/pull/98) base one the discussed information, please help to review it when you are free.
Because we will support multi-registry in the future, so I use follow style to store the credential information in aa-offline_fs_kbc-resources.json:
```
"Credential.<registry>": "base64('user:password')"
```
and the <registry> value is from ResourceDescription request message like
```
{
    "name": "credential",
    "optional": {
        "registry": "...",
    },
}
```
if there is no optional be set in ResourceDescription request message, then the code will use `Credential` as the key to query credential information.

**Comment by Xynnn007** [comment]
> @stevenhorsman @Xynnn007 @jialez0 I create [a pr](https://github.com/confidential-containers/attestation-agent/pull/98) base one the discussed information, please help to review it when you are free. Because we will support multi-registry in the future, so I use follow style to store the credential information in aa-offline_fs_kbc-resources.json:
> 
> ```
> "Credential.<registry>": "base64('user:password')"
> ```
> 
> and the value is from ResourceDescription request message like
> 
> ```
> {
>     "name": "credential",
>     "optional": {
>         "registry": "...",
>     },
> }
> ```
> 
> if there is no optional be set in ResourceDescription request message, then the code will use `Credential` as the key to query credential information.

Hey @liudalibj, thanks for that PR. Shall we turn to `auth.json` scheme now. Could you please change the resource content to  `auth.json`-like? 

like 
```json
{
    "auths": {
		"<registry>": {
			"auth": "<base64-encoded-<username:password>>"
		},
        }
}
```
##### Referrers

https://github.com/containers/image/blob/main/docs/containers-auth.json.5.md
https://github.com/Xynnn007/image-rs/blob/feat-auth/docs/image_auth.md

**Comment by liudalibj** [comment]
Updated the pr to use `auth.json` style.

**Comment by liudalibj** [comment]
@Xynnn007 the Referrers look very good. 
Only one thing under https://github.com/Xynnn007/image-rs/blob/feat-auth/docs/image_auth.md#authentication section.

>3. The image-rs module then match the entries inside the auth.json using longest prefix match. In this story, the match result will be "auth": "QWxpY2U6cHN3ZAo=". If no entries is matched, use Anonymous authentication in step 4.

Is it better?
> 3. The image-rs module then match the entries inside the auth.json using longest prefix match (`private-registry.org`). In this story, the match result will be "auth": "QWxpY2U6cHN3ZAo=". If no entries is matched, use Anonymous authentication in step 4.
